name: test

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Tokyo

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          # node-version-file: 'package.json'
          package-manager-cache: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - id: pnpm-store
        run: echo "dir=$(pnpm store path --silent)" | tee -a "$GITHUB_OUTPUT"
      - id: cache-key
        run: >
          echo 'suffix=${{ format('{0}-{1}-{2}', runner.os, runner.arch, hashFiles('pnpm-lock.yaml')) }}'
          | tee -a "$GITHUB_OUTPUT"
      - uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ steps.pnpm-store.outputs.dir }}
          key: pnpm-store-${{ steps.cache-key.outputs.suffix }}
          restore-keys: |
            pnpm-store-
      - id: restore-cache
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: node_modules
          key: pnpm-modules-${{ steps.cache-key.outputs.suffix }}
      - if: steps.restore-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
      - run: pnpm test
      - if: github.ref_name == 'main'
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ steps.pnpm-store.outputs.dir }}
          key: pnpm-store-${{ steps.cache-key.outputs.suffix }}
      - if: github.ref_name == 'main'
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: node_modules
          key: pnpm-modules-${{ steps.cache-key.outputs.suffix }}
